### PR TITLE
Added variable to be able to find other browser,

### PR DESCRIPTION
**Pull request by gmerzu**
i.e.:
let g:vim_markdown_preview_browser = 'Chromium'

### CODE REVIEW

**Comment by JamshedVesuna** [comment]
@gmerzu good idea. Is there any reason you want a globally scoped variable?

**Comment by gmerzu** [comment]
Probably this is an ugly fix, but a lot of users use Chromium browser, and the plugin doesn't provide a way to neither use it by a user nor autodetect. I like your extension and wish to use it from the upstream. So it would be great if you provided the ability to use more browsers such as Chromium ;) Thanks

**Comment by JamshedVesuna** [comment]
@gmerzu I took you're pull request and made some modifications and updates. Does a9971e1051efd238c7a77f7d7af96eb33cdb6fb9 fix this issue? As you have in your PR, you can just rename `Google Chrome` on [line 7](https://github.com/JamshedVesuna/vim-markdown-preview/blob/master/plugin/vim-markdown-preview.vim#L7) to `Chromium`. 

I added a few more things as well. Thanks agin for this PR.

**Comment by gmerzu** [comment]
Ok. thanks for you changes. But why wouldn't you like to consider also a global variable for set up a browser outside the plugin? This is useful alongside plugin managers such as Vundle. If I do some modifications to your plugin, I will need to revert them back before all plugins updating. It is somehow the general way to use global variables to configure a plugin.:)

**Comment by JamshedVesuna** [comment]
Can you explain this further? My understanding is that you want `b:vim_markdown_preview_browser` to be `g:vim_markdown_preview_browser` so you can use the variable `vim_markdown_preview_browser` with other plugins?

Right now, the user simply fills in `b:vim_markdown_preview_browser` with the name of their browser. This would be very easy to replicate elsewhere. However, if you feel that it would be useful, feel free to update your pull request with the latest commits and I'll merge it in.

**Comment by gmerzu** [comment]
closed as there has been opened a new request

**Pull request closed without merging**
