### PR TITLE
OSX improvements

### PR DESCRIPTION
**Pull request by letorbi**
By default the plugin opens the temporary HTML file with the default program for HTML files. For me this is not Safari, but vim itself, so the preview is pretty useless.

This pull request add the browser name defined in `vim_markdown_preview_browser` to the `open` command line, so that the defined preview browser is actually used (regardless of the default application associated with HTML files). Apart from that it also changes the default value of `vim_markdown_preview_browser` from "Google Chrome" to "Safari" on OSX.

### CODE REVIEW

**Comment by JamshedVesuna** [comment]
I really like the idea of this PR, thank you! Some people use a different browser (other than Safari) on OS X, so it would be good to overwrite `vim_markdown_preview_browser` if it exists globally.

**Comment by letorbi** [comment]
The PR uses Safari as default if no other browser has been defined in a global `vim_markdown_preview_browser`. If `vim_markdown_preview_browser` exists globally, that value will be used instead of the default value.

Commit 1107411 does not change anything except for using `'Safari'` instead of `'Google Chome'` as default value on OSX. The other commits don't affect the value of `vim_markdown_preview_browser` at all.

I hope, this clarifies everything. Please write me, if things are still unclear. I'd really like to see this PR merged...

**Comment by JamshedVesuna** [comment]
@letorbi Thanks for the PR! I really like the idea of using the `-a` flag with `open`. However, the OS selection has been refactored in 7826214df1cf0313ef074fe19712d015d49aaed3. Mind updating your PR to remove any merge conflicts?

**Comment by letorbi** [comment]
HI, I've merged the latest master, so all conflicts should be resolved now.

**Comment by letorbi** [comment]
Hej, would you mind to merge this PR? Would be great :)

**Comment by JamshedVesuna** [comment]
Thanks @letorbi!

**Pull request merged**
